{
    'name': 'Production planning',
    'version': '14.0.1.0.0',
    'category': 'Manufacturing/Manufacturing',
    'summary': 'Production planning',
    'author': 'Divergent Catalist ERP Solutions',
    'company': 'Divergent Catalist ERP Solutions',
    'maintainer': 'Divergent Catalist ERP Solutions',
    'website': 'https://www.catalisterp.com/',
    'depends': ['base', 'uom', 'mail', 'mrp', 'stock', 'sale_management', 'sale', 'uom'
                ],
    'data': [
        'security/security.xml',
        'security/record_rules.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/mail_template.xml',
        'report/rent_items_report_config.xml',
        'report/rent_items_pdf_report.xml',
        'views/product_template_view.xml',
        'views/sale_order_view.xml',
        'views/event_date_calender.xml',
        'views/account_move_view.xml',
        'views/production_view.xml',
        'views/mrp_production_view.xml',
        'views/stock_picking_type_view.xml',
        'views/rent_items_views.xml',
        'views/rented_items_list_view.xml',
    ],
    'qweb': [],

    'installable': True,
    'application': True,
    'auto_install': False,
}
