{
    'name': 'Employee Exit Clearance',
    'version': '14.0.1.0.0',
    'summary': """Employee Exit Clearance""",
    'depends': ['base', 'hr', 'mail', 'hr_resignation'],
    'data': ['security/ir.model.access.csv',
             'security/security.xml',
             'data/sequence.xml',
             'views/resignation_department.xml',
             'views/hr_employee_inherit.xml',
             'views/exit_clearane.xml'],
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'AGPL-3',
}
