{
    'name': 'Payroll Customization',
    'version': '14.0.1.0.0',
    'summary': 'Payroll Customization',
    'author': 'Divergent Catalist ERP Solutions',
    'company': 'Divergent Catalist ERP Solutions',
    'maintainer': 'Divergent Catalist ERP Solutions',
    'website': 'https://www.catalisterp.com/',
    'depends': ['hr', 'om_hr_payroll'],
    'category': 'Generic Modules/Human Resources',
    'data': ['security/security.xml',
             'security/ir.model.access.csv',
             'views/additional_input_rule_view.xml',
             'views/hr_employee_views.xml',
             'views/hr_payslip_view.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
}