# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Day Book Report',
    'version': '14.0.1.0.0',
    'summary': 'Print Day Book Report Through Wizard',
    'author': 'Divergent Catalist ERP Solutions',
    'company': 'Divergent Catalist ERP Solutions',
    'maintainer': 'Divergent Catalist ERP Solutions',
    'sequence': 10,
    'description': """Print Day Book Report Through Wizard,
        Filter Day Book Report Details by Date""",
    'category': 'Accounting',
    'website': 'https://www.catalisterp.com/',
    'depends': ['base', 'account', 'contacts'],
    'data': ['security/ir.model.access.csv',
             'wizard/day_book_wizard.xml',
             'report/day_book_report.xml',
             'report/day_report_report_temp.xml'],
    'demo': [],
    'qweb': [],
    'licenSe': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
