{
    'name': 'Petty Cash Management',
    'version': '14.0.1.0.0',
    'category': 'Account',
    'summary': 'Petty Cash Management',
    'author': 'Divergent Catalist ERP Solutions',
    'company': 'Divergent Catalist ERP Solutions',
    'maintainer': 'Divergent Catalist ERP Solutions',
    'website': 'https://www.catalisterp.com/',
    'depends': ['base', 'stock','account'],
    'data': ['security/ir.model.access.csv',
             'security/record_rule.xml',
             'data/sequence.xml',
             'views/petty_cash_management.xml',
             'views/petty_cash_in_acnt.xml'],
    'qweb': [],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
