# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Balance Sheet & Profit and Loss(PDF & Excel)',
    'version': '14.0.1.0.0',
    'summary': 'Balance Sheet & Profit and Loss(PDF & Excel) Through Wizard',
    'author': 'Divergent Catalist ERP Solutions',
    'company': 'Divergent Catalist ERP Solutions',
    'maintainer': 'Divergent Catalist ERP Solutions',
    'sequence': 10,
    'description': """Print Balance Sheet & Profit and Loss(PDF & Excel) Through Wizard,
        Filter Report Details by Date, Account Head,....""",
    'category': 'Accounting',
    'website': 'https://www.catalisterp.com/',
    'depends': ['base', 'account', 'contacts', 'tb_report'],
    'data': ['security/ir.model.access.csv',
             'views/account_account_type.xml',
             'wizard/balance_sheet_wizard.xml',
             'wizard/profit_loss_wizard.xml',
             'report/report.xml',
             'report/profit_loss_report_temp.xml',
             'report/balance_sheet_report_temp.xml'],
    'demo': [],
    'qweb': [],
    'licenSe': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
