{'name': 'sale_order_po_button',
 'version': '14.0.1.0.0',
 'summary': 'Sale Order PO Button ',
 'sequence': -1,
 'category': 'Tools',
 'author': 'Catalist Divergent ERP',
 'maintainer': 'Catalist Divergent ERP',
 'company': 'Catalist Divergent ERP',
 'website': 'https://www.catalisterp.com/',
 'depends': ['base','sale','purchase'],
 'data': ['security/ir.model.access.csv',
          'wizard/sale_order_po_button_wizard.xml',
          'views/sale_order_po_button.xml'],

 'images': [],
 'license': 'AGPL-3',
 'installable': True,
 'application': False,
 'auto_install': False,
 }